# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSDevelopTools' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IOSDevelopTools

  target 'IOSDevelopToolsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IOSDevelopToolsUITests' do
    # Pods for testing
  end

end
